name: Android Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  issues: write

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        working-directory: src
        run: make build-sync

      - name: Install Java & Gradle
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Make Gradle Wrapper Executable
        run: chmod +x src/android/gradlew

      - name: Get Version from Package.json
        id: get_version
        working-directory: src/web
        run: |
          echo "VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV

      - name: Bump version
        uses: chkfung/android-version-actions@v1.2.2
        with:
          gradlePath: src/android/app/build.gradle
          versionCode: ${{github.run_number}}
          versionName: ${{ env.VERSION }}

      - name: Build APK and AAB
        working-directory: src/android
        run: ./gradlew bundleRelease

      - name: Sign App
        id: sign_app
        uses: ilharp/sign-android-release@v1.0.4
        with:
          releaseDir: src/android/app/build/outputs/bundle/release
          signingKey: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          keyAlias: ${{ secrets.ANDROID_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          buildToolsVersion: 35.0.0
      - name: Upload APK as an Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Android-App
          path: src/android/app/build/outputs/bundle/release

  release:
    needs: build-android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Built APK
        uses: actions/download-artifact@v4
        with:
          name: Android-App
          path: src/android/app/build/outputs/bundle/release/

      - name: Get Version from Package.json
        id: get_version
        working-directory: src/web
        run: |
          echo "VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}
          name: "Einbürgerungstest v${{ env.VERSION }}"
          draft: false
          prerelease: false
          files: src/android/app/build/outputs/bundle/release/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
