install:
	 npm install
build:
	 npm run build
sync:
	 npx cap sync
sync-android:
	npx cap sync android
sync-ios:
	npx cap sync android
build-sync:install build sync
build-start:install build
	npm run start