install:
	 npm install
build:
	 npm run build
sync: install
	 npx cap sync
sync-android: install
	npx cap sync android
sync-ios: install
	npx cap sync android
build-sync: build sync
build-start: build
	npm run start